context:
  name: apache-airflow-providers-pgvector
  version: "1.7.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_pgvector-${{ version }}.tar.gz
  sha256: dc8755257f889a1294ec031c552f2efbdc311a1c97614ccb85fc281f42723d52

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.8.0
    - apache-airflow-providers-postgres >=6.6.0
    - pgvector-python >=0.3.1

tests:
  - python:
      imports:
        - airflow.providers.pgvector
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-pgvector for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-pgvector/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
